### ISSUE TITLE
Cannot find recipe snddist/build.sh for package build.

### ISSUE THREAD

**Issue by yang-zhibin** [SND-LHC/sndsw#167] opened 2023-10-04 08:35 UTC
Hi, I tried to set up sndsw on my MacBook following [On systems without access to CVMFS](https://github.com/SND-LHC/sndsw#on-systems-without-access-to-cvmfs).

When I ran `aliBuild build sndsw -c snddist` this occurred:
```
aliBuild: error: Default 'o2' does not exists. Viable options:
- release
```
Then I tried to run `aliDoctor build sndsw -c snddist `, it shows:
```
ERROR: Cannot find recipe snddist/build.sh for package build.
usage: aliBuild [-h] [-d] [-n]
                {analytics,architecture,build,clean,deps,doctor,init,version}
                ...
aliBuild: error: Default `o2' does not exists. Viable options:
- release
```

**Comment by ThomasRuf** [comment] 2023-10-04 08:37
Try:

aliBuild build sndsw -c snddist --defaults release

Von: yang-zhibin ***@***.***>
Gesendet: Wednesday, 4 October 2023 10:36
An: SND-LHC/sndsw ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [SND-LHC/sndsw] Cannot find recipe snddist/build.sh for package build. (Issue #167)


Hi, I tried to set up sndsw on my MacBook following On systems without access to CVMFS<https://github.com/SND-LHC/sndsw#on-systems-without-access-to-cvmfs>.

When I ran aliBuild build sndsw -c snddist this occurred:

aliBuild: error: Default 'o2' does not exists. Viable options:

- release

Then I tried to run aliDoctor build sndsw -c snddist , it shows:

ERROR: Cannot find recipe snddist/build.sh for package build.

usage: aliBuild [-h] [-d] [-n]

                {analytics,architecture,build,clean,deps,doctor,init,version}

                ...

aliBuild: error: Default `o2' does not exists. Viable options:

- release

**Comment by olantwin** [comment] 2023-10-04 10:16
Since Thomas helped with the first issue, let me point out the second error:

> Then I tried to run `aliDoctor build sndsw -c snddist `, it shows:
> 
> ```
> ERROR: Cannot find recipe snddist/build.sh for package build.
> usage: aliBuild [-h] [-d] [-n]
> ```

When using aliDoctor, you need to remove the `build` from the command. You will also need to specify the default `release` when using a newer aliBuild version.

You're trying to build the software on macOS?

**Comment by olantwin** [comment] 2023-10-04 10:18
Duplicate of https://github.com/SND-LHC/sndsw/issues/151. Please check open issues before creating a new one.

**Comment by yang-zhibin** [comment] 2023-10-04 12:39
> aliBuild build sndsw -c snddist --defaults release

Here is what I got from`aliBuild build sndsw -c snddist --defaults release`:
```
ERROR: The following packages are system requirements and could not be found:
ERROR:
ERROR: - osx-system-openssl
ERROR:
ERROR: Please run:
ERROR:
ERROR: 	aliDoctor --defaults release sndsw
ERROR:
ERROR: to get a full diagnosis.
```

Here is the diagnosis of `aliDoctor --defaults release sndsw`:
```
usage: aliBuild [-h] [-d] [-n] {analytics,architecture,build,clean,deps,doctor,init,version} ...
aliBuild: error: Wrong path to alidist specified: alidist
```

Is this because there is something wrong with my aliBuild installation?

**Comment by yang-zhibin** [comment] 2023-10-04 12:40
> Since Thomas helped with the first issue, let me point out the second error:
> 
> > Then I tried to run `aliDoctor build sndsw -c snddist `, it shows:
> > ```
> > ERROR: Cannot find recipe snddist/build.sh for package build.
> > usage: aliBuild [-h] [-d] [-n]
> > ```
> 
> When using aliDoctor, you need to remove the `build` from the command. You will also need to specify the default `release` when using a newer aliBuild version.
> 
> You're trying to build the software on macOS?

Thank you for the correction. Yes, I am trying to build the software on macOS.

**Comment by yang-zhibin** [comment] 2023-10-04 12:47
> Duplicate of #151. Please check open issues before creating a new one.

Sorry for that! Actually, I have checked all the open issues and also tried the solution on https://github.com/SND-LHC/sndsw/issues/151 before. It mentioned $SNDDIST and alias sndBuild, I thought it was about [On lxplus or systems with CVMFS](https://github.com/SND-LHC/sndsw#on-lxplus-or-systems-with-cvmfs).

Sorry for the inconvenience.

**Comment by ThomasRuf** [comment] 2023-10-04 12:50
No, nothing wrong with aliBuild.  You are missing a system library, osx-system-openssl. You need to check how you can install this on your Mac.

Thomas

Von: yang-zhibin ***@***.***>
Gesendet: Wednesday, 4 October 2023 14:40
An: SND-LHC/sndsw ***@***.***>
Cc: Thomas Ruf ***@***.***>; Comment ***@***.***>
Betreff: Re: [SND-LHC/sndsw] Cannot find recipe snddist/build.sh for package build. (Issue #167)


aliBuild build sndsw -c snddist --defaults release

Here is what I got fromaliBuild build sndsw -c snddist --defaults release:

ERROR: The following packages are system requirements and could not be found:

ERROR:

ERROR: - osx-system-openssl

ERROR:

ERROR: Please run:

ERROR:

ERROR:  aliDoctor --defaults release sndsw

ERROR:

ERROR: to get a full diagnosis.

Here is the diagnosis of aliDoctor --defaults release sndsw:

usage: aliBuild [-h] [-d] [-n] {analytics,architecture,build,clean,deps,doctor,init,version} ...

aliBuild: error: Wrong path to alidist specified: alidist

Is this because there is something wrong with my aliBuild installation?

**Comment by olantwin** [comment] 2023-10-04 13:25
> ```
> usage: aliBuild [-h] [-d] [-n] {analytics,architecture,build,clean,deps,doctor,init,version} ...
> aliBuild: error: Wrong path to alidist specified: alidist
> ```
> 
> Is this because there is something wrong with my aliBuild installation?

Please do what the error message says: specify the path to `snddist` (our equivalent to alidist).

**Comment by olantwin** [comment] 2023-10-04 13:29
> Thank you for the correction. Yes, I am trying to build the software on macOS.

Sndsw currently is not developed on macOS as none of the developers use macOS. While there should be no fundamental reasons why it should not work, getting all the dependencies to work will likely take a lot of debugging. I would not discourage you from trying, but it won't be easy!

I'd be happy to help debug different compatibility issues, for which you should open issues in the snddist repo.

For most use cases, I would recommend using lxplus, a virtual machine or docker.

**Comment by olantwin** [comment] 2023-10-04 13:34
> > Duplicate of #151. Please check open issues before creating a new one.
> 
> Sorry for that! Actually, I have checked all the open issues and also tried the solution on #151 before. It mentioned $SNDDIST and alias sndBuild, I thought it was about [On lxplus or systems with CVMFS](https://github.com/SND-LHC/sndsw#on-lxplus-or-systems-with-cvmfs).
> 
> Sorry for the inconvenience.

Indeed, Thomas responded with the instructions for lxplus there by accident. The solution to that problem is specifying `--default release`, which fixes that issue no matter whether you're on lxplus or local.

**Comment by yang-zhibin** [comment] 2023-10-04 14:04
> > Thank you for the correction. Yes, I am trying to build the software on macOS.
> 
> Sndsw currently is not developed on macOS as none of the developers use macOS. While there should be no fundamental reasons why it should not work, getting all the dependencies to work will likely take a lot of debugging. I would not discourage you from trying, but it won't be easy!
> 
> I'd be happy to help debug different compatibility issues, for which you should open issues in the snddist repo.
> 
> For most use cases, I would recommend using lxplus, a virtual machine or docker.

I have successfully built sndsw on lxplus before, it seems fine except it's a bit slow when I run the event display program. Maybe it's because of the XQuart I used, it's just slow and crashes very often. To solve this, I imagine I will need to install a new GUI on the lxplus or try to install sndsw locally. This is why I am trying to install it on my Macbook.

**Comment by yang-zhibin** [comment] 2023-10-04 14:20
> No, nothing wrong with aliBuild. You are missing a system library, osx-system-openssl. You need to check how you can install this on your Mac. Thomas

Thank you very much! It's starting to build the software.

**Comment by olantwin** [comment] 2023-11-02 14:42
Since the original issue (wrong invocation of `aliDoctor` is fixed (and wasn't an issue with sndsw in the first place!)), I'll go ahead and close this.

Feel free to open issues or pull requests in [snddist](https://github.com/SND-LHC/snddist) concerning the build on macOS.

**Closed by olantwin** 2023-11-02 14:42 UTC
Labels: duplicate
